### ISSUE TITLE
Change suds for zeep

### ISSUE THREAD

**Issue by agutierrezrodriguez** [codingjoe/django-vies#154]
Currently suds is abandoned, update library to another with support as Zeep (http://docs.python-zeep.org/en/master/)

**Comment by codingjoe** [comment]
Hi @agutierrezrodriguez good idea. I am using zeep in many other projects now. It's a great library.
I can't wait for your pull request 😉

**Comment by hiaselhans** [comment]
fixed with #156 
no..?

**Comment by codingjoe** [comment]
True, thanks @hiaselhans
