### ISSUE TITLE
New releases missing on PyPI?

### ISSUE THREAD

**Issue by nijel** [codingjoe/django-vies#162]
Is it intentional that new releases are missing from PyPI? See https://pypi.org/project/django-vies/

**Comment by codingjoe** [comment]
@nijel thanks, apparently, I didn't upgrade this package to auto versioning yet, so I increased the number myself.

Released in [5.0.1](https://github.com/codingjoe/django-vies/releases/tag/5.0.1)

**Comment by codingjoe** [comment]
I double-checked, now it's there.
