### ISSUE TITLE
Distribution is missing the compiled messages files

### ISSUE THREAD

**Issue by allcaps** [codingjoe/django-vies#171]
Most packages ship with `*.mo` files (compiled `*.po`). They are missing from the django-vies distribution.

- `django-admin complilemessages` will create `django.mo` files.
- `recursive-include vies/locale *` in `MANIFEST.in` should be sufficient to include these files in the packages.

**Comment by codingjoe** [comment]
Hi @allcaps,

Thanks for reaching out. I honestly didn't notice the `mo`-files were missing from the wheels. I will create a patch fixing that.
However, they should never be included in the repository or source packages. They should be complied during build time. I will also adapt the script, so it builds correctly for builds from the repo or a tar ball.

Best,
Joe

**Comment by allcaps** [comment]
Agreed, sure!

FYI: I just forked and added the *.mo to version control on my fork, so I can install from git, and push my project forward. 
This is a temp workaround until a django-vies release with mo files is available.

Thank you for your quick responses and actions! 👏

**Comment by allcaps** [comment]
Ah, 6.0.2 is out. Great! ❤️  🥳
