### ISSUE TITLE
Error in IE validation

### ISSUE THREAD

**Issue by chripede** [codingjoe/django-vies#20]
The current validation for IE VAT numbers does not accept this format: IE1234567XX

For instance IE3286438VH is not accepted, even though it's a valid VAT number.
See https://www.gov.uk/guidance/vat-eu-country-codes-vat-numbers-and-vat-in-other-languages

**Comment by codingjoe** [comment]
hi @chripede, can you change the regex here to make it work?
https://github.com/codingjoe/django-vies/blob/master/vies/__init__.py#L57
