### ISSUE TITLE
'ValueError' object has no attribute 'message'

### ISSUE THREAD

**Issue by Godod** [codingjoe/django-vies#26]
Hello. When I try to save model with undefined country, I get ValueError, which this message:

```
'ValueError' object has no attribute 'message'
```

Exception Location:	python3.5/site-packages/vies/fields.py in compress, line 45

**Comment by codingjoe** [comment]
Seems like there is a error raised and not properly handled. Would you mind providing me with the stack trace?

**Comment by Godod** [comment]
Hello. Sorry for late answer. I will try reproduce the bug and them copy-paste the stack trace

**Comment by Godod** [comment]
Hello again. I can't reproduce the bug anymore. This bug is fixed right now. At 45 line I don't see *message* attribute on ValueError. Sorry for my dishonesty and carelessness

**Comment by codingjoe** [comment]
@Godod don't worry. Every feedback is appreciated. Never hesitate to report a potential bug!
Thanks!
