### ISSUE TITLE
Usage of models.VATINField including VATINValidator

### ISSUE THREAD

**Issue by rm--** [codingjoe/django-vies#32]
We tried to use the model field `VATINField` including its validator without the form field. But it doesn't work as expected. The documentation says:

>```
>from vies.models import VATINField
>from vies.validators import VATINValidator
>
>
>class Company(models.Model):
>    name = models.CharField(max_length=100)
>    vat = VATINField(validators=VATINValidator(verify=True, validate=True))
>```

There is a typo in the documentation. It should be `vat = VATINField(validators=[VATINValidator(verify=True, validate=True)])` because [model field validators should be a list](https://docs.djangoproject.com/en/1.9/ref/models/fields/#validators).

After that change, the `VATINValidator` ends with the following message:
> AttributeError: 'str' object has no attribute 'verify'

The `VATINValidator` expects a `VATIN object` but a `Python String` is given. Do we use the `VATINField` in a wrong way?

I created a small PR that changes the `vies.VATINValidator` to handle `VATIN objects` and `Python Strings`. And fixes the typo. ;)

**Comment by rjrjhaverkamp** [comment]
I am getting the same error: `'str' object has no attribute 'verify'`. Trying to add vat numbers from the admin panel. Is there anything that still needs to be done on the pull request?

**Comment by codingjoe** [comment]
I'll try to look into the PR tomorrow and release a new version asap. Sorry that I didn't reply earlier.

**Comment by rm--** [comment]
The issue can be closed.
