### ISSUE TITLE
AttributeError: 'VATIN' object has no attribute 'result'

### ISSUE THREAD

**Issue by jvw1954** [codingjoe/django-vies#35]
"jaap@jaap:~$ sudo pip install -e git://github.com/codingjoe/django-vies.git#egg=django-vies
Obtaining django-vies from git+git://github.com/codingjoe/django-vies.git#egg=django-vies
  Cloning git://github.com/codingjoe/django-vies.git to ./src/django-vies
  Running setup.py (path:/home/jaap/src/django-vies/setup.py) egg_info for package django-vies

  Installing extra requirements: 'egg'
Requirement already satisfied (use --upgrade to upgrade): suds-jurko>=0.6 in /usr/local/lib/python2.7/dist-packages (from django-vies)
Requirement already satisfied (use --upgrade to upgrade): retrying>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from django-vies)
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.0 in /usr/lib/python2.7/dist-packages (from retrying>=1.1.0->django-vies)
Installing collected packages: django-vies
  Running setup.py develop for django-vies
    processing file django.po in /home/jaap/src/django-vies/vies/locale/nl/LC_MESSAGES
    processing file django.po in /home/jaap/src/django-vies/vies/locale/da/LC_MESSAGES
    processing file django.po in /home/jaap/src/django-vies/vies/locale/de/LC_MESSAGES

    Creating /usr/local/lib/python2.7/dist-packages/django-vies.egg-link (link to .)
    Adding django-vies 3.1.0 to easy-install.pth file

    Installed /home/jaap/src/django-vies
Successfully installed django-vies
Cleaning up...
jaap@jaap:~$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from vies.types import VATIN
>>> vat = VATIN('NL', '124851903B01')
>>> vat.is_valid()
True
>>> vat.result
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'VATIN' object has no attribute 'result'
>>>"

**Comment by codingjoe** [comment]
Hi, it's `vat.data` now, good catch, that was changed in the last major release. The change was not reflected in the documentation, but is now.
Thanks again, for the contribution!
