### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by piaph** [codingjoe/django-vies#45]
We would like to be able to configure all logging in our own settings file, but it seems like this line in [__init.py__](https://github.com/codingjoe/django-vies/blob/master/vies/__init__.py) prevents this:

`logging.getLogger('suds.client').setLevel(logging.INFO)`

Would it be possible to let users control this in their own settings instead?

**Comment by codingjoe** [comment]
Sure why not, it might be best to just drop this line? What do you think?
Feel free to submit a patch!
